#!/bin/bash

IGNOREEXIT=24
IGNOREOUT='^(file has vanished: |rsync warning: some files vanished before they could be transferred)'

set -o pipefail

rsync --stats "${@}" 2>&1 | (egrep -v "$IGNOREOUT" || true)
ret=$?
if [[ $ret == $IGNOREEXIT ]]; then
    ret=0
fi
if [[ $ret != 0 ]]; then
  echo "rsnapshot exit code: ${ret}, args: ${@}" | logger
fi

exit $ret
